name: changelog
true:
  pull_request:
    types:
    - opened
    - synchronize
    - reopened
    - labeled
    - unlabeled
    branches:
    - main
permissions: read-all
jobs:
  changelog:
    runs-on: ubuntu-latest
    if: false
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
    - name: Check for CHANGELOG changes
      run: "# Only the latest commit of the feature branch is available\n# automatically.\
        \ To diff with the base branch, we need to\n# fetch that too (and we only\
        \ need its latest commit).\ngit fetch origin ${{ github.base_ref }} --depth=1\n\
        if [[ $(git diff --name-only FETCH_HEAD | grep CHANGELOG) ]]\nthen\n  echo\
        \ \"A CHANGELOG was modified. Looks good!\"\nelse\n  echo \"No CHANGELOG was\
        \ modified.\"\n  echo \"Please add a CHANGELOG entry, or add the \\\"Skip\
        \ Changelog\\\" label if not required.\"\n  false\nfi\n"
