name: Protect released changelog
true:
  pull_request:
    types:
    - opened
    - synchronize
    - reopened
    - labeled
    - unlabeled
permissions: read-all
jobs:
  protect-released-changelog:
    runs-on: ubuntu-latest
    if: false
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
    - name: Protect the released changelog
      run: './verify_released_changelog.sh ${{ github.base_ref }}

        '
